# Copyright (c) Innofactor Plc & AUTHORS
# SPDX-License-Identifier: BSD-3-Clause
#
---
name: "Deploy"
on:
  workflow_call:
    inputs:
      auto_merge:
        description: "Auto merge method to use after successful deployment."
        required: false
        default: "squash"
        type: string
      azure_client_id:
        description: "The client ID of the service principal for Azure login."
        required: false
        default: ""
        type: string
      azure_providers:
        description: "A comma separated list of Azure resource providers."
        required: false
        default: ""
        type: string
      azure_provider_wait_count:
        description: "Times to check provider status before giving up."
        required: false
        default: 30
        type: number
      azure_provider_wait_seconds:
        description: "Seconds to wait between each provider status check."
        required: false
        default: 10
        type: number
      azure_subscription_id:
        description: "The subscription ID in which to deploy the resources."
        required: false
        default: ""
        type: string
      azure_tenant_id:
        description: "The tenant ID in which the subscription exists."
        required: false
        default: ""
        type: string
      cost_threshold:
        description: "Max acceptable estimated cost."
        required: false
        default: -1
        type: number
      currency:
        description: "Currency code to use for estimations."
        required: false
        default: "EUR"
        type: string
      environment:
        description: "The GitHub environment name to use for the create job."
        required: false
        default: "production"
        type: string
      location:
        description: "The Azure location to store the deployment metadata."
        required: false
        default: "westeurope"
        type: string
      log_severity:
        description: "The log verbosity."
        required: false
        default: "ERROR"
        type: string
      management_group:
        description: "Management group to create deployment at for mg scope."
        required: false
        default: ""
        type: string
      resource_group:
        description: "Resource group to create deployment at for group scope."
        required: false
        default: ""
        type: string
      rule_baseline:
        description: "The name of a PSRule baseline to use."
        required: false
        default: "Azure.Default"
        type: string
      rule_modules:
        description: "A comma separated list of modules to use for analysis."
        required: false
        default: "Az.Resources,PSRule.Rules.Azure"
        type: string
      rule_option:
        description: "The path to an options file."
        required: false
        default: ""
        type: string
      scope:
        description: "The deployment scope. Accepted: tenant, mg, sub, group."
        required: false
        default: "sub"
        type: string
      template:
        description: "The template address."
        required: false
        default: "main.bicep"
        type: string
      template_parameters:
        description: "Deployment parameter values."
        required: false
        default: ""
        type: string
      version_ace_tool:
        description: "Azure Cost Estimator version."
        required: false
        default: "1.4"
        type: string
    secrets:
      AZURE_CLIENT_ID:
        description: "The client ID of the service principal for Azure login."
        required: false
      AZURE_CLIENT_SECRET:
        description: "The service principal secret used for Azure login."
        required: false
      AZURE_SUBSCRIPTION_ID:
        description: "The subscription ID in which to deploy the resources."
        required: false
      AZURE_TENANT_ID:
        description: "The tenant ID in which the subscription exists."
        required: false

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions: {}

jobs:
  plan:
    name: "🗓️ Plan"
    permissions:
      contents: read # for checkout_src
      id-token: write # for login_open_id
      pull-requests: write # for comment
    outputs:
      providers: ${{ steps.plan.outputs.providers }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Plan
        id: plan
        uses: innofactororg/bicep-action/.github/actions/plan@beta6
        with:
          azure_client_id: ${{ inputs.azure_client_id || secrets.AZURE_CLIENT_ID }}
          azure_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          azure_providers: ${{ inputs.azure_providers }}
          azure_subscription_id: ${{ inputs.azure_subscription_id || secrets.AZURE_SUBSCRIPTION_ID }}
          azure_tenant_id: ${{ inputs.azure_tenant_id || secrets.AZURE_TENANT_ID }}
          cost_threshold: ${{ inputs.cost_threshold }}
          currency: ${{ inputs.currency }}
          location: ${{ inputs.location }}
          log_severity: ${{ inputs.log_severity }}
          management_group: ${{ inputs.management_group }}
          resource_group: ${{ inputs.resource_group }}
          rule_baseline: ${{ inputs.rule_baseline }}
          rule_modules: ${{ inputs.rule_modules }}
          rule_option: ${{ inputs.rule_option }}
          scope: ${{ inputs.scope }}
          template: ${{ inputs.template }}
          template_parameters: ${{ inputs.template_parameters }}
          token: ${{ github.token }}
          version_ace_tool: ${{ inputs.version_ace_tool }}

  create:
    name: "🏃 Create"
    needs: plan
    environment: ${{ inputs.environment }}
    permissions:
      contents: write # for auto_merge
      id-token: write # for login_open_id
      pull-requests: write # for comment
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
        with:
          persist-credentials: false
          fetch-depth: 1

      - name: Deploy
        id: deploy
        uses: innofactororg/bicep-action/.github/actions/deploy@beta6
        with:
          auto_merge: ${{ inputs.auto_merge }}
          azure_client_id: ${{ inputs.azure_client_id || secrets.AZURE_CLIENT_ID }}
          azure_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          azure_providers: ${{ needs.plan.outputs.providers }}
          azure_provider_wait_count: ${{ inputs.azure_provider_wait_count }}
          azure_provider_wait_seconds: ${{ inputs.azure_provider_wait_seconds }}
          azure_subscription_id: ${{ inputs.azure_subscription_id || secrets.AZURE_SUBSCRIPTION_ID }}
          azure_tenant_id: ${{ inputs.azure_tenant_id || secrets.AZURE_TENANT_ID }}
          location: ${{ inputs.location }}
          log_severity: ${{ inputs.log_severity }}
          management_group: ${{ inputs.management_group }}
          resource_group: ${{ inputs.resource_group }}
          scope: ${{ inputs.scope }}
          template: ${{ inputs.template }}
          template_parameters: ${{ inputs.template_parameters }}
          token: ${{ github.token }}
